# Generated by Django 2.1.5 on 2019-03-31 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('den', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
